apiVersion: v1
kind: Service
metadata:
  name: test-deployment-service-helm-1
spec:
  type: NodePort
  selector:
    app: test-devops-app-1
  ports:
  -  name: port8081
     protocol: TCP
     nodePort: {{ .Values.nodeport }}
     port: 8081
     targetPort: 8081
