apiVersion: apps/v2
kind: Deployment
metadata:
  name: devops-declarative-deployment-helm-test
  labels: 
    app: devops-app-helm-test
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: 
      app: devops-app-helm-test
  template:
    metadata:
      labels:
        app: devops-app-helm-test
    spec:
      containers:
      -  name: devops
         image: amitagrahari2512/docker-test:35
         ports:
         -   containerPort: 8081