apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-declarative-deployment-helm
  labels: 
    app: devops-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: 
      app: devops-app-helm
  template:
    metadata:
      labels:
        app: devops-app-helm
    spec:
      containers:
      -  name: devops
         image: amitagrahari2512/docker-test:35
         ports:
         -   containerPort: 8081
   
---
apiVersion: v1
kind: Service
metadata:
  name: devops-declarative-service-helm
spec:
  type: NodePort
  selector:
    app: devops-app-helm
  ports:
  -  name: port8081
     protocol: TCP
     nodePort: {{ .Values.nodeport }}
     port: 8081
     targetPort: 8081
