apiVersion: v2
kind: Service
metadata:
  name: devops-declarative-service-helm-test
spec:
  type: NodePort
  selector:
    app: devops-app-helm-test
  ports:
  -  name: port8081
     protocol: TCP
     nodePort: {{ .Values.nodeport }}
     port: 8081
     targetPort: 8081

